#### Задание 1 

In [2]:
import numpy as np

In [6]:
a = np.array([[1,6],
             [2,8],
             [3,11],
            [3,10],
            [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

#### Задание 2

In [12]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [19]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [23]:
a_centered_sp/(a_centered.shape[0]-1)

2.0

#### Задание 4

In [29]:
b = np.cov(a.T)

In [30]:
b[0,1]

2.0